# Generated by Django 5.1.2 on 2024-10-19 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('session', models.CharField(max_length=50)),
                ('pair', models.CharField(max_length=20)),
                ('buy_sell', models.CharField(max_length=4)),
                ('time_frame', models.CharField(max_length=20)),
                ('win_lose', models.CharField(max_length=4)),
                ('lot_size', models.FloatField()),
                ('closed_pips', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='DataEntry',
        ),
    ]
