# Generated by Django 5.1.2 on 2024-10-19 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_marketdata_delete_dataentry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marketdata',
            name='time',
        ),
        migrations.AlterField(
            model_name='marketdata',
            name='buy_sell',
            field=models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], max_length=10),
        ),
        migrations.AlterField(
            model_name='marketdata',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='marketdata',
            name='lot_size',
            field=models.CharField(choices=[('half', 'Half'), ('full', 'Full')], max_length=10),
        ),
        migrations.AlterField(
            model_name='marketdata',
            name='pair',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='marketdata',
            name='session',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='marketdata',
            name='time_frame',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='marketdata',
            name='win_lose',
            field=models.CharField(choices=[('win', 'Win'), ('lose', 'Lose')], max_length=10),
        ),
    ]
